### ISSUE TITLE
Error forwarding the new session Empty pool of VM for setup Capabi lities [{count=1, browserName=chrome}]

### ISSUE THREAD

**Issue by vs0562** [angular/protractor#1226]
Server runs fine: getting response in the Chrome when navigated to the http://localhost:4444/wd/hub

However when trying to run conf.js:
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['integration/buildingCodes/buildingCodesTest.js']
}
getting the exception below:

node_modules\protractor\bin>node protractor 
std\winplatform\platform8\engineandcloud\trunk\Axon\Axon.Portal\UnitTests\conf.j
s
Using the selenium server at http://localhost:4444/wd/hub

node_modules\protractor\node_modules\selenium-webdriver\lib\at
oms\error.js:109
  var template = new Error(this.message);
                 ^
UnknownError: Error forwarding the new session Empty pool of VM for setup Capabi
lities [{count=1, browserName=chrome}]
    at new bot.Error (node_modules\protractor\node_modules\sel
enium-webdriver\lib\atoms\error.js:109:18)
    at Object.bot.response.checkResponse (node_modules\protrac
tor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at node_modules\protractor\node_modules\selenium-webdriver
\lib\webdriver\webdriver.js:134:24
    at node_modules\protractor\node_modules\selenium-webdriver
\lib\goog\base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (node_modu
les\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)

```
at notify (node_modules\protractor\node_modules\selenium-w
```

ebdriver\lib\webdriver\promise.js:362:12)
    at notifyAll (node_modules\protractor\node_modules\seleniu
m-webdriver\lib\webdriver\promise.js:331:7)
    at resolve (node_modules\protractor\node_modules\selenium-
webdriver\lib\webdriver\promise.js:309:7)
    at fulfill (node_modules\protractor\node_modules\selenium-
webdriver\lib\webdriver\promise.js:429:5)
    at node_modules\protractor\node_modules\selenium-webdriver
\lib\goog\base.js:1243:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (node_modu
les\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:131:49
)
    at Function.webdriver.WebDriver.createSession (node_module
s\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:111:30)
    at Builder.build (node_modules\protractor\node_modules\sel
enium-webdriver\builder.js:106:20)
    at HostedDriverProvider.getDriver (node_modules\protractor
\lib\driverProviders\hosted.js:54:9)
    at node_modules\protractor\lib\runner.js:221:35
    at _fulfilled (node_modules\protractor\node_modules\q\q.js
:797:54)
    at self.promiseDispatch.done (node_modules\protractor\node
_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (node_modules\protracto
r\node_modules\q\q.js:759:13)
    at node_modules\protractor\node_modules\q\q.js:525:49

**Comment by oraclemohammadi** [comment]
Hi juliemr
What is the difference when we use -role hub in command line? I have the same problem and when I get rid of -role hub it works as you told.  When I see http://localhost:4444/wd/hub I get the following :

"message": "Session [(null externalkey)] not available and is not among the last 1000 terminated sessions.\nActive sessions are[]",
		"class": "org.openqa.grid.common.exception.GridException",
		"stackTrace": [
			{
				"fileName": "ActiveTestSessions.java",
				"className": "org.openqa.grid.internal.ActiveTestSessions",
				"methodName": "getExistingSession",
				"lineNumber": 110
			},

**Comment by sbulusu** [comment]
After some more investigation, i found this info.

That exception "Error forwarding the new session Empty pool of VM" means that your Selenium Grid doesn't have any node available with a browser that has the desired capabilities.

If you're running Selenium Grid as a hub on your machine (-role hub) make sure that at least one node which provides the desired browser is connected to that hub. Check out http://localhost:4444/grid/console to see whether any nodes are connected to your hub.

**Comment by udayanem** [comment]
I am getting same above error when running Selenium Grid from Jenkins. As i am running from Jenkins with Selenium plugin, i am not using **-role hub**. How to overcome this error here?

**Comment by Gnoq** [comment]
I'm having the same trouble. Although I configure Selenium to run in Docker. Checking out [](http://localhost:4444/grid/console), I had any nodes running.

**Comment by srghma** [comment]
```
#!/bin/sh -e
#
# This file has been authored by Sergei Khoma in 2018-2019 and Anton Smagin in
# 2018-2019
#
# (C) copyright by Greenbadger LLC
#

# idea stolen from https://gist.github.com/nicerobot/1136dcfba6ce3da67ce3ded5101a4078

# USAGE
# /bin/wait-chrome-connected-to-hub http://$HUB_HOST:$HUB_PORT

hub_url="$1"

# Retries a command on failure (idea stolen from http://fahdshariff.blogspot.com/2014/02/retrying-commands-in-shell-scripts.html).
# $1 - the max number of attempts
# $2 - the seconds to sleep
# $3... - the command to run
retry() {
  max_attempts="$1"; shift
  seconds="$1"; shift
  cmd="$@"
  attempt_num=1

  until $cmd
  do
    if [ $attempt_num -eq $max_attempts ]
    then
      echo "Attempt $attempt_num failed and there are no more attempts left!"
      return 1
    else
      echo "Attempt $attempt_num failed! Trying again in $seconds seconds..."
      attempt_num=`expr "$attempt_num" + 1`
      sleep "$seconds"
    fi
  done
}

check_connected () {
  curl --silent --fail --connect-timeout 40 $hub_url/grid/console | grep "browserName: chrome" > /dev/null
}

retry 5 1 check_connected

echo >&2 "$(date +%Y%m%dt%H%M%S) Chrome is conneted to hub"
```


```
hub:
  image: elgalu/selenium
  volumes:
    - /dev/shm:/dev/shm
  privileged: true
  environment:
    - SELENIUM_HUB_HOST=hub
    - SELENIUM_HUB_PORT=4444
    - GRID=true
    - CHROME=false
    - FIREFOX=false
    - NOVNC=false
    - VNC_START=false

chrome:
  image: elgalu/selenium
  privileged: true
  environment:
    - SELENIUM_HUB_HOST=hub
    - SELENIUM_HUB_PORT=4444
    - SCREEN_WIDTH=1880
    - SCREEN_HEIGHT=1040
    - VIDEO=false
    - GRID=false
    - CHROME=true
    - FIREFOX=false
    - CHROME_ADDITIONAL_ARGS=--ignore-certificate-errors
    # - SELENIUM_NODE_HOST={{CONTAINER_IP}} # not working
    - SELENIUM_NODE_HOST=0.0.0.0
  volumes:
    - downloads:/downloads
    - /dev/shm:/dev/shm
    - ../../fixtures:/fixtures:ro

feature_tests:
  image: node....
  command: |
    sh -c "
    /bin/waitforit -host=$$CLIENT_HOST -port=$$CLIENT_PORT -timeout=30 &&
    /bin/waitforit -host=$$HUB_HOST -port=$$HUB_PORT -timeout=30 &&
    /bin/waitforit -host=$$MAILHOG_HOST -port=$$MAILHOG_PORT -timeout=30 &&
    /bin/waitforit -host=$$POSTGRES_HOST -port=$$POSTGRES_PORT -timeout=20 &&
    /bin/wait-chrome-connected-to-hub http://$$HUB_HOST:$$HUB_PORT &&
    (curl --silent --fail --connect-timeout 40 $$CLIENT_URL > /dev/null) &&
    exec npm run test"
  volumes:
    - ../../scripts/waitforit:/bin/waitforit:ro
    - ../../scripts/wait-chrome-connected-to-hub:/bin/wait-chrome-connected-to-hub:ro
  environment:
    CLIENT_HOST: client
    CLIENT_PORT: 3000
    CLIENT_URL:  http://client:3000

    HUB_URL:  http://hub:4444/wd/hub
    HUB_HOST: hub
    HUB_PORT: 4444

    POSTGRES_USER:     app_admin
    POSTGRES_PASSWORD: app_admin_pass
    POSTGRES_HOST:     postgres
    POSTGRES_PORT:     5432
    POSTGRES_DB:       gb_test

    MAILHOG_URL:  http://mailhog:8025
    MAILHOG_HOST: mailhog
    MAILHOG_PORT: 8025
```
